/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author faiz
 */
public class DashboardAdmin extends javax.swing.JFrame implements View{

    /**
     * Creates new form Login
     */
    public DashboardAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundKlug1 = new img.BackgroundKlug();
        btnPengguna = new javax.swing.JButton();
        judul = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        close1 = new javax.swing.JLabel();
        btnKelas = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        welkom = new javax.swing.JLabel();
        btnAkun = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);

        backgroundKlug1.setMaximumSize(new java.awt.Dimension(800, 600));
        backgroundKlug1.setMinimumSize(new java.awt.Dimension(800, 600));
        backgroundKlug1.setPreferredSize(new java.awt.Dimension(800, 600));

        btnPengguna.setBackground(new java.awt.Color(255, 255, 255));
        btnPengguna.setFont(new java.awt.Font("Aller", 0, 24)); // NOI18N
        btnPengguna.setForeground(new java.awt.Color(238, 95, 1));
        btnPengguna.setText("Kelola Pengguna");
        btnPengguna.setBorderPainted(false);

        judul.setFont(new java.awt.Font("Aller", 0, 36)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 255));
        judul.setText("Dashboard Administrator");

        close.setBackground(new java.awt.Color(255, 255, 255));
        close.setFont(new java.awt.Font("Aller", 0, 18)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeMouseReleased(evt);
            }
        });

        close1.setBackground(new java.awt.Color(255, 255, 255));
        close1.setFont(new java.awt.Font("Aller", 0, 18)); // NOI18N
        close1.setForeground(new java.awt.Color(255, 255, 255));
        close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                close1MouseReleased(evt);
            }
        });

        btnKelas.setBackground(new java.awt.Color(255, 255, 255));
        btnKelas.setFont(new java.awt.Font("Aller", 0, 24)); // NOI18N
        btnKelas.setForeground(new java.awt.Color(238, 95, 1));
        btnKelas.setText("Kelola Kelas");
        btnKelas.setBorderPainted(false);

        btn_logout.setBackground(new java.awt.Color(255, 255, 255));
        btn_logout.setFont(new java.awt.Font("Aller", 0, 24)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(238, 95, 1));
        btn_logout.setText("Logout");
        btn_logout.setBorderPainted(false);

        welkom.setFont(new java.awt.Font("Aller", 0, 24)); // NOI18N
        welkom.setForeground(new java.awt.Color(238, 95, 1));
        welkom.setText("Welkom");

        btnAkun.setBackground(new java.awt.Color(255, 255, 255));
        btnAkun.setFont(new java.awt.Font("Aller", 0, 24)); // NOI18N
        btnAkun.setForeground(new java.awt.Color(238, 95, 1));
        btnAkun.setText("Akun");
        btnAkun.setBorderPainted(false);

        javax.swing.GroupLayout backgroundKlug1Layout = new javax.swing.GroupLayout(backgroundKlug1);
        backgroundKlug1.setLayout(backgroundKlug1Layout);
        backgroundKlug1Layout.setHorizontalGroup(
            backgroundKlug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundKlug1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(backgroundKlug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPengguna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAkun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundKlug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundKlug1Layout.createSequentialGroup()
                        .addComponent(judul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(close1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundKlug1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(welkom)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        backgroundKlug1Layout.setVerticalGroup(
            backgroundKlug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundKlug1Layout.createSequentialGroup()
                .addGroup(backgroundKlug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundKlug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(close1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addComponent(close, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(backgroundKlug1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(judul)))
                .addGap(82, 82, 82)
                .addGroup(backgroundKlug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPengguna)
                    .addComponent(welkom))
                .addGap(18, 18, 18)
                .addComponent(btnKelas)
                .addGap(23, 23, 23)
                .addComponent(btnAkun)
                .addGap(18, 18, 18)
                .addComponent(btn_logout)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundKlug1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundKlug1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void close1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseReleased
        this.setState(DashboardAdmin.ICONIFIED);
    }//GEN-LAST:event_close1MouseReleased

    private void closeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseReleased
        System.exit(0);
    }//GEN-LAST:event_closeMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private img.BackgroundKlug backgroundKlug1;
    private javax.swing.JButton btnAkun;
    private javax.swing.JButton btnKelas;
    private javax.swing.JButton btnPengguna;
    private javax.swing.JButton btn_logout;
    private javax.swing.JLabel close;
    private javax.swing.JLabel close1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel welkom;
    // End of variables declaration//GEN-END:variables

    public JButton getBtn_logout() {
        return btn_logout;
    }

    public JButton getBtnPengguna() {
        return btnPengguna;
    }

    public JButton getBtnKelas() {
        return btnKelas;
    }
    
    public void setWelkom(String isi) {
        welkom.setText(isi);
    }
    
    public void setJudul(String isi) {
        judul.setText(isi);
    }

    public JButton getBtnAkun() {
        return btnAkun;
    }
    
    @Override
    public void addActionListener(ActionListener e) {
        btn_logout.addActionListener(e);
        btnPengguna.addActionListener(e);
        btnKelas.addActionListener(e);
    }
}
