/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author faiz
 */
public class QuizMahasiswa extends javax.swing.JFrame implements View{

    /**
     * Creates new form Login
     */
    public QuizMahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        backgroundKlug1 = new img.BackgroundKlug();
        judulHalaman = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        close1 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pilihQuiz = new javax.swing.JList<>();
        judul = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        soal = new javax.swing.JTextArea();
        btn_finish = new javax.swing.JButton();
        jawaban1 = new javax.swing.JRadioButton();
        jawaban2 = new javax.swing.JRadioButton();
        jawaban3 = new javax.swing.JRadioButton();
        jawaban4 = new javax.swing.JRadioButton();
        jawaban5 = new javax.swing.JRadioButton();
        btn_tambah = new javax.swing.JButton();
        jaw1 = new javax.swing.JTextField();
        jaw2 = new javax.swing.JTextField();
        jaw3 = new javax.swing.JTextField();
        jaw4 = new javax.swing.JTextField();
        jaw5 = new javax.swing.JTextField();
        btn_hapus = new javax.swing.JButton();
        judulQuiz = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);

        backgroundKlug1.setMaximumSize(new java.awt.Dimension(800, 600));
        backgroundKlug1.setMinimumSize(new java.awt.Dimension(800, 600));
        backgroundKlug1.setPreferredSize(new java.awt.Dimension(800, 600));

        judulHalaman.setFont(new java.awt.Font("Aller", 0, 36)); // NOI18N
        judulHalaman.setForeground(new java.awt.Color(255, 255, 255));
        judulHalaman.setText("Quiz");

        close.setBackground(new java.awt.Color(255, 255, 255));
        close.setFont(new java.awt.Font("Aller", 0, 18)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeMouseReleased(evt);
            }
        });

        close1.setBackground(new java.awt.Color(255, 255, 255));
        close1.setFont(new java.awt.Font("Aller", 0, 18)); // NOI18N
        close1.setForeground(new java.awt.Color(255, 255, 255));
        close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                close1MouseReleased(evt);
            }
        });

        btn_back.setBackground(new java.awt.Color(255, 255, 255));
        btn_back.setFont(new java.awt.Font("Aller", 0, 24)); // NOI18N
        btn_back.setForeground(new java.awt.Color(238, 95, 1));
        btn_back.setText("Kembali");
        btn_back.setBorderPainted(false);

        jLabel1.setFont(new java.awt.Font("Aller", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 95, 1));
        jLabel1.setText("Daftar Quiz");

        pilihQuiz.setFont(new java.awt.Font("Aller", 0, 18)); // NOI18N
        pilihQuiz.setForeground(new java.awt.Color(238, 95, 1));
        pilihQuiz.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        pilihQuiz.setSelectionBackground(new java.awt.Color(238, 95, 1));
        jScrollPane1.setViewportView(pilihQuiz);

        judul.setFont(new java.awt.Font("Aller", 0, 24)); // NOI18N
        judul.setForeground(new java.awt.Color(238, 95, 1));
        judul.setText("Quiz");

        soal.setEditable(false);
        soal.setColumns(20);
        soal.setRows(2);
        soal.setText("Soal");
        jScrollPane2.setViewportView(soal);

        btn_finish.setBackground(new java.awt.Color(255, 255, 255));
        btn_finish.setFont(new java.awt.Font("Aller", 0, 18)); // NOI18N
        btn_finish.setForeground(new java.awt.Color(238, 95, 1));
        btn_finish.setText("Finish");
        btn_finish.setBorderPainted(false);

        buttonGroup1.add(jawaban1);
        jawaban1.setFont(new java.awt.Font("Aller", 0, 12)); // NOI18N
        jawaban1.setForeground(new java.awt.Color(238, 95, 1));
        jawaban1.setSelected(true);
        jawaban1.setText("Jawaban1");
        jawaban1.setOpaque(false);

        buttonGroup1.add(jawaban2);
        jawaban2.setFont(new java.awt.Font("Aller", 0, 12)); // NOI18N
        jawaban2.setForeground(new java.awt.Color(238, 95, 1));
        jawaban2.setText("Jawaban2");
        jawaban2.setOpaque(false);

        buttonGroup1.add(jawaban3);
        jawaban3.setFont(new java.awt.Font("Aller", 0, 12)); // NOI18N
        jawaban3.setForeground(new java.awt.Color(238, 95, 1));
        jawaban3.setText("Jawaban3");
        jawaban3.setOpaque(false);

        buttonGroup1.add(jawaban4);
        jawaban4.setFont(new java.awt.Font("Aller", 0, 12)); // NOI18N
        jawaban4.setForeground(new java.awt.Color(238, 95, 1));
        jawaban4.setText("Jawaban4");
        jawaban4.setOpaque(false);

        buttonGroup1.add(jawaban5);
        jawaban5.setFont(new java.awt.Font("Aller", 0, 12)); // NOI18N
        jawaban5.setForeground(new java.awt.Color(238, 95, 1));
        jawaban5.setText("Jawaban5");
        jawaban5.setOpaque(false);

        btn_tambah.setBackground(new java.awt.Color(255, 255, 255));
        btn_tambah.setFont(new java.awt.Font("Aller", 0, 18)); // NOI18N
        btn_tambah.setForeground(new java.awt.Color(238, 95, 1));
        btn_tambah.setText("Tambah");
        btn_tambah.setBorderPainted(false);

        btn_hapus.setBackground(new java.awt.Color(255, 255, 255));
        btn_hapus.setFont(new java.awt.Font("Aller", 0, 18)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(238, 95, 1));
        btn_hapus.setText("Hapus");
        btn_hapus.setBorderPainted(false);

        judulQuiz.setFont(new java.awt.Font("Aller", 0, 36)); // NOI18N

        javax.swing.GroupLayout backgroundKlug1Layout = new javax.swing.GroupLayout(backgroundKlug1);
        backgroundKlug1.setLayout(backgroundKlug1Layout);
        backgroundKlug1Layout.setHorizontalGroup(
            backgroundKlug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundKlug1Layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(judulHalaman)
                .addGroup(backgroundKlug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundKlug1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 401, Short.MAX_VALUE)
                        .addComponent(close1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(backgroundKlug1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(judulQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(backgroundKlug1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(backgroundKlug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(backgroundKlug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(backgroundKlug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(judul)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundKlug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(backgroundKlug1Layout.createSequentialGroup()
                                .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_finish, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(backgroundKlug1Layout.createSequentialGroup()
                        .addComponent(jawaban4)
                        .addGap(18, 18, 18)
                        .addComponent(jaw4))
                    .addGroup(backgroundKlug1Layout.createSequentialGroup()
                        .addComponent(jawaban3)
                        .addGap(18, 18, 18)
                        .addComponent(jaw3))
                    .addGroup(backgroundKlug1Layout.createSequentialGroup()
                        .addComponent(jawaban2)
                        .addGap(18, 18, 18)
                        .addComponent(jaw2))
                    .addGroup(backgroundKlug1Layout.createSequentialGroup()
                        .addComponent(jawaban5)
                        .addGap(18, 18, 18)
                        .addComponent(jaw5))
                    .addGroup(backgroundKlug1Layout.createSequentialGroup()
                        .addComponent(jawaban1)
                        .addGap(18, 18, 18)
                        .addComponent(jaw1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundKlug1Layout.setVerticalGroup(
            backgroundKlug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundKlug1Layout.createSequentialGroup()
                .addGroup(backgroundKlug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundKlug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(close1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addComponent(close, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(backgroundKlug1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(backgroundKlug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(judulHalaman)
                            .addComponent(judulQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(56, 56, 56)
                .addGroup(backgroundKlug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(judul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundKlug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundKlug1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backgroundKlug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jawaban1)
                            .addComponent(jaw1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(backgroundKlug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jawaban2)
                            .addComponent(jaw2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundKlug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jawaban3)
                            .addComponent(jaw3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundKlug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jawaban4)
                            .addComponent(jaw4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundKlug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jawaban5)
                            .addComponent(jaw5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btn_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundKlug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_back)
                    .addComponent(btn_finish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundKlug1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundKlug1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void close1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseReleased
        this.setState(QuizMahasiswa.ICONIFIED);
    }//GEN-LAST:event_close1MouseReleased

    private void closeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseReleased
        System.exit(0);
    }//GEN-LAST:event_closeMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private img.BackgroundKlug backgroundKlug1;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_finish;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_tambah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel close;
    private javax.swing.JLabel close1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jaw1;
    private javax.swing.JTextField jaw2;
    private javax.swing.JTextField jaw3;
    private javax.swing.JTextField jaw4;
    private javax.swing.JTextField jaw5;
    private javax.swing.JRadioButton jawaban1;
    private javax.swing.JRadioButton jawaban2;
    private javax.swing.JRadioButton jawaban3;
    private javax.swing.JRadioButton jawaban4;
    private javax.swing.JRadioButton jawaban5;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel judulHalaman;
    private javax.swing.JTextField judulQuiz;
    private javax.swing.JList<String> pilihQuiz;
    private javax.swing.JTextArea soal;
    // End of variables declaration//GEN-END:variables

    public JButton getBtn_back() {
        return btn_back;
    }

    public JButton getBtn_tambah() {
        return btn_tambah;
    }
    
    public JButton getBtn_hapus() {
        return btn_hapus;
    }
    
    public JList getPilihQuiz(){
        return pilihQuiz;
    }

    public JButton getBtn_finish() {
        return btn_finish;
    }
    
    public JLabel getJudul(){
        return judul;
    }
    
    public JTextArea getSoal(){
        return soal;
    }
    
    public JLabel getJudulHalaman(){
        return judulHalaman;
    }

    public JTextField getJudulQuiz() {
        return judulQuiz;
    }
    

    public JRadioButton getJawaban(int i) {
        switch (i) {
            case 1:
                return jawaban1;
            case 2:
                return jawaban2;
            case 3:
                return jawaban3;
            case 4:
                return jawaban4;
            default:
                return jawaban5;
        }
    }
    
    public JTextField getJaw(int i) {
        switch (i) {
            case 1:
                return jaw1;
            case 2:
                return jaw2;
            case 3:
                return jaw3;
            case 4:
                return jaw4;
            default:
                return jaw5;
        }
    }
//
//    public JRadioButton getJawaban1() {
//        return jawaban1;
//    }
//
//    public JRadioButton getJawaban2() {
//        return jawaban2;
//    }
//
//    public JRadioButton getJawaban3() {
//        return jawaban3;
//    }
//
//    public JRadioButton getJawaban4() {
//        return jawaban4;
//    }
//
//    public JRadioButton getJawaban5() {
//        return jawaban5;
//    }
//    
    @Override
    public void addActionListener(ActionListener e) {
        btn_back.addActionListener(e);
        jawaban1.addActionListener(e);
        jawaban2.addActionListener(e);
        jawaban3.addActionListener(e);
        jawaban4.addActionListener(e);
        jawaban5.addActionListener(e);
    }

    @Override
    public synchronized void addMouseListener(MouseListener l) {
        pilihQuiz.addMouseListener(l);
    }

}
